### ISSUE TITLE
0.13.3: provider aws module check FAILED, unable to find plugin

### ISSUE THREAD

**Issue by augusto-gregorio** [cloudgraphdev/cli#7]
I updated the cli to the latest version and now im having this issue
![Screen Shot 2021-11-02 at 13 17 32](https://user-images.githubusercontent.com/82825489/139905126-eda5b013-38ae-4b0a-a505-75d4da27b57b.png)
:

**Comment by tyler-dunkel** [comment]
@augusto-gregorio sorry we had an issue moving between the latest versions due to an issue with our runtime plugin manager. Can you try uninstalling cloudgraph using something like `npm uninstall -g @cloudgraphdev/cli` and then reinstalling `npm install -g @cloudgraphdev/cli`. And see if the issue persists? Sorry about this!

**Comment by tyler-dunkel** [comment]
perfect thank you!

**Comment by augusto-gregorio** [comment]
It seems cloufgraphdev is not in the registry

npm install -g @cloudgraphdev/cli
npm ERR! code E404
npm ERR! 404 Not Found - GET https://registry.npmjs.org/@cloudgraphdev%2fcli - Not found
npm ERR! 404 
npm ERR! 404  '@cloudgraphdev/cli@*' is not in this registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404 
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/augustogregorio/.npm/_logs/2021-11-02T16_31_46_903Z-debug.log

**Comment by augusto-gregorio** [comment]
In my previous install i used this package @cloudgraph/cli without dev

**Comment by tyler-dunkel** [comment]
ahh yes sorry drop the dev part, that is my fault!

**Comment by augusto-gregorio** [comment]
This is odd, when i reinstall it and execute cg init, i have an error that also removes de package and npm.

❯ cg init
ℹ Found config for cloudGraph, using...
ℹ Dgraph host set as: http://localhost:8997
ℹ No lock file found for Cloud Graph, creating one...
ℹ Installing aws module version: latest
✔ aws plugin installed successfully!
undefined:1


SyntaxError: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at /usr/local/lib/node_modules/@cloudgraph/cli/lib/manager/npm/index.js:60:34
    at ChildProcess.exithandler (node:child_process:404:5)
    at ChildProcess.emit (node:events:390:28)
    at maybeClose (node:internal/child_process:1062:16)
    at Socket.<anonymous> (node:internal/child_process:448:11)
    at Socket.emit (node:events:390:28)
    at Pipe.<anonymous> (node:net:687:12)

Node.js v17.0.1
❯ npm
zsh: command not found: npm
❯ cg
zsh: command not found: cg

**Comment by tyler-dunkel** [comment]
ok wow that is super weird, sorry we are still working out the kinks with our new plugin manager :/. If you are ok with reinstalling, could you run `CG_DEBUG=5 cg init` and see if it provides us with some extra debugging information? I appreciate your help with this!

**Comment by augusto-gregorio** [comment]
Yeah sure, i love to help.
Now is not removing the package but still the same other issue, here is the complete log:
`❯ CG_DEBUG=5 cg init
ℹ Found config for cloudGraph, using...
ℹ Dgraph host set as: http://localhost:8997
ℹ No lock file found for Cloud Graph, creating one...
ℹ Installing aws module version: latest
✔ aws plugin installed successfully!
ℹ Error: Cannot find module '@cloudgraph/cg-provider-aws/package.json'
Require stack:
- /usr/local/lib/node_modules/@cloudgraph/cli/lib/manager/index.js
- /usr/local/lib/node_modules/@cloudgraph/cli/lib/commands/base.js
- /usr/local/lib/node_modules/@cloudgraph/cli/lib/commands/init.js
- /usr/local/lib/node_modules/@cloudgraph/cli/node_modules/@oclif/config/lib/plugin.js
- /usr/local/lib/node_modules/@cloudgraph/cli/node_modules/@oclif/config/lib/config.js
- /usr/local/lib/node_modules/@cloudgraph/cli/node_modules/@oclif/config/lib/index.js
- /usr/local/lib/node_modules/@cloudgraph/cli/node_modules/@oclif/command/lib/command.js
- /usr/local/lib/node_modules/@cloudgraph/cli/node_modules/@oclif/command/lib/index.js
- /usr/local/lib/node_modules/@cloudgraph/cli/bin/run
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
    at Function.Module._load (node:internal/modules/cjs/loader:778:27)
    at Module.require (node:internal/modules/cjs/loader:999:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at /usr/local/lib/node_modules/@cloudgraph/cli/lib/manager/index.js:114:87
    at async Manager.checkRequiredVersion (/usr/local/lib/node_modules/@cloudgraph/cli/lib/manager/index.js:114:26)
    at async Manager.getPlugin (/usr/local/lib/node_modules/@cloudgraph/cli/lib/manager/index.js:61:40)
    at async Init.getProviderClient (/usr/local/lib/node_modules/@cloudgraph/cli/lib/commands/base.js:131:48)
    at async Init.run (/usr/local/lib/node_modules/@cloudgraph/cli/lib/commands/init.js:120:28)
    at async Init._run (/usr/local/lib/node_modules/@cloudgraph/cli/node_modules/@oclif/command/lib/command.js:43:20)
✖ Error: provider aws module check FAILED, unable to find plugin
    at Manager.getPlugin (/usr/local/lib/node_modules/@cloudgraph/cli/lib/manager/index.js:80:19)
    at async Init.getProviderClient (/usr/local/lib/node_modules/@cloudgraph/cli/lib/commands/base.js:131:48)
    at async Init.run (/usr/local/lib/node_modules/@cloudgraph/cli/lib/commands/init.js:120:28)
    at async Init._run (/usr/local/lib/node_modules/@cloudgraph/cli/node_modules/@oclif/command/lib/command.js:43:20)
    at async Config.ctx.config.runCommand (/usr/local/lib/node_modules/@cloudgraph/cli/node_modules/@tiagonapoli/oclif-plugin-spaced-commands/lib/hooks/init.js:90:9)
    at async Main.run (/usr/local/lib/node_modules/@cloudgraph/cli/node_modules/@oclif/command/lib/main.js:27:9)
    at async Main._run (/usr/local/lib/node_modules/@cloudgraph/cli/node_modules/@oclif/command/lib/command.js:43:20)
⚠ There was an error installing or requiring a plugin for aws, does one exist?
ℹ For more information on this error, please see https://github.com/cloudgraphdev/cli#common-errors
⚠ There was an issue initializing aws plugin, skipping...
ℹ CloudGraph config found...
? Would you like to change CloudGraph config No
ℹ Note that none of your cloud's information is ever sent to or stored by CloudGraph or third parties`

**Comment by mfranceschit** [comment]
Hey, @augusto-gregorio, thanks for helping us to fix this. Do you mind giving us more details about the platform you're using?. That would be helpful. Thanks

**Comment by augusto-gregorio** [comment]
Glad to help
MacOS Monterrey

**Comment by mfranceschit** [comment]
I see, please let me know about the following questions when you have a chance:
- Which version of Node.js do you have? 
- Which version of npm are you using? 
- Do you use some version manager like nvm?

**Comment by augusto-gregorio** [comment]
Node: v17.0.1
Npm: 8.1.0
And i dont use nvm.

**Comment by tyler-dunkel** [comment]
@augusto-gregorio we are working to try to fix this right now. We will hopefully have a new version up soon with some fixes. Appreciate your help and patience!

**Comment by augusto-gregorio** [comment]
thanks both of you, i really like the product, so no worries, i'll wait for the fix.

**Comment by mfranceschit** [comment]
We released a potential fix for this issue as an alpha version. You can access that version using the following command: 

`npm install -g @cloudgraph/cli@0.13.0-alpha.5`

Let us know how it goes. Thanks for the patience.

**Comment by augusto-gregorio** [comment]
it works perfectly, thanks a lot guys.

**Comment by tyler-dunkel** [comment]
Great! thanks for your patience and help on this issue!

**Comment by akulbe** [comment]
I am having issues with the aws provider as well, and I even tried with installing the latest version of cloudgraph. @mfranceschit 

`  cloudvana  akulbe  ~  CG_DEBUG=5 cg init
ℹ Found config for cloudGraph, using...
ℹ Dgraph host set as: http://localhost:8997
? Which cloud provider would you like to use? aws
ℹ aws
ℹ No lock file found for Cloud Graph, creating one...
ℹ Installing aws module version: latest
ℹ Error: Command failed: node_modules/.bin/npm install @cloudgraph/cg-provider-aws@latest --no-audit --no-fund --ignore-scripts --silent

    at ChildProcess.exithandler (node:child_process:397:12)
    at ChildProcess.emit (node:events:390:28)
    at maybeClose (node:internal/child_process:1064:16)
    at Process.ChildProcess._handle.onexit (node:internal/child_process:301:5)
✖ Manager failed to install provider plugin for aws
✖ Error: provider aws module check FAILED, unable to find plugin
    at Manager.getPlugin (/usr/local/lib/node_modules/@cloudgraph/cli/lib/manager/index.js:79:19)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Init.getProviderClient (/usr/local/lib/node_modules/@cloudgraph/cli/lib/commands/base.js:137:84)
    at async Init.run (/usr/local/lib/node_modules/@cloudgraph/cli/lib/commands/init.js:131:32)
    at async Init._run (/usr/local/lib/node_modules/@cloudgraph/cli/node_modules/@oclif/core/lib/command.js:67:22)
    at async Config.runCommand (/usr/local/lib/node_modules/@cloudgraph/cli/node_modules/@oclif/core/lib/config/config.js:268:25)
    at async Object.run (/usr/local/lib/node_modules/@cloudgraph/cli/node_modules/@oclif/core/lib/main.js:73:5)
⚠ There was an error installing or requiring a plugin for aws, does one exist?
ℹ For more information on this error, please see https://github.com/cloudgraphdev/cli#common-errors
⚠ There was an issue initializing aws plugin, skipping...
ℹ CloudGraph config found...
? Would you like to change CloudGraph config No
ℹ Note that none of your cloud's information is ever sent to or stored by CloudGraph or third parties
✔ Your config has been successfully stored at /home/akulbe/.config/cloudgraph/.cloud-graphrc.json
✔ Your data will be stored at /home/akulbe/.local/share/cloudgraph/cg`

**Comment by tyler-dunkel** [comment]
@akulbe thanks for reporting. Can you please share your OS?

**Comment by akulbe** [comment]
`  cloudvana  akulbe  ~  cat /etc/os-release
NAME="AlmaLinux"
VERSION="8.5 (Arctic Sphynx)"
ID="almalinux"
ID_LIKE="rhel centos fedora"
VERSION_ID="8.5"
PLATFORM_ID="platform:el8"
PRETTY_NAME="AlmaLinux 8.5 (Arctic Sphynx)"
ANSI_COLOR="0;34"
CPE_NAME="cpe:/o:almalinux:almalinux:8::baseos"
HOME_URL="https://almalinux.org/"
DOCUMENTATION_URL="https://wiki.almalinux.org/"
BUG_REPORT_URL="https://bugs.almalinux.org/"

ALMALINUX_MANTISBT_PROJECT="AlmaLinux-8"
ALMALINUX_MANTISBT_PROJECT_VERSION="8.5"`

**Comment by tyler-dunkel** [comment]
@mfranceschit can you take a look at this?

**Comment by mfranceschit** [comment]
Hey @akulbe good to know, you're trying the CG CLI. I ran some tests using the configuration below, and everything seem to work. Do you mind providing us with more details? In that way, we can validate your case. Thank you

node 16.13.1
npm 8.5.5

<img width="340" alt="image" src="https://user-images.githubusercontent.com/6466697/160487998-47acc3ca-5bc6-46a7-8677-94996d2afe87.png">

**Comment by akulbe** [comment]
I'm not sure what else to provide. Fresh install of AlmaLinux. Install AWS CLI, install Node using modules. Install Cloudgraph from the [tutorial](https://hackernoon.com/a-complete-inventory-of-your-aws-footprint-in-5-minutes).

I just tried the same exact thing with a brand new Ubuntu 21.10. It failed to install there, as well.

It fails at the `cg init aws` step.

**Comment by tyler-dunkel** [comment]
Can you provide the output of `cg -v`?

**Comment by tyler-dunkel** [comment]
@akulbe This does seem to be an odd issue. Would you be open for a zoom call with one of our engs so we could debug further? otherwise we will continue to try to reproduce on our end. Again, thank you for bringing this to our attention!

**Comment by akulbe** [comment]
Absolutely, but you'll have bring some patience and understanding to the table. I can't talk normally as my vocal cords are injured. I can only whisper.

**Comment by akulbe** [comment]
> Can you provide the output of `cg -v`?
> 
> Also can you run the init command in debug mode? Might provide us a little more info.
> 
> `CG_DEBUG=5 cg init aws`

I provided this for the AlmaLinux distro in my initial comment. Here it is for Ubuntu 21.10

`(.venv) akulbe@cloudvana:~$ CG_DEBUG=5 cg init
ℹ Found config for cloudGraph, using...
ℹ Dgraph host set as: http://localhost:8997
? Which cloud provider would you like to use? aws
ℹ aws
ℹ No lock file found for Cloud Graph, creating one...
ℹ Installing aws module version: latest
ℹ Error: Command failed: node_modules/.bin/npm install @cloudgraph/cg-provider-aws@latest --no-audit --no-fund --ignore-scripts --silent

    at ChildProcess.exithandler (node:child_process:398:12)
    at ChildProcess.emit (node:events:527:28)
    at maybeClose (node:internal/child_process:1090:16)
    at Process.ChildProcess._handle.onexit (node:internal/child_process:302:5)
✖ Manager failed to install provider plugin for aws
✖ Error: provider aws module check FAILED, unable to find plugin
    at Manager.getPlugin (/usr/lib/node_modules/@cloudgraph/cli/lib/manager/index.js:79:19)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Init.getProviderClient (/usr/lib/node_modules/@cloudgraph/cli/lib/commands/base.js:137:84)
    at async Init.run (/usr/lib/node_modules/@cloudgraph/cli/lib/commands/init.js:131:32)
    at async Init._run (/usr/lib/node_modules/@cloudgraph/cli/node_modules/@oclif/core/lib/command.js:67:22)
    at async Config.runCommand (/usr/lib/node_modules/@cloudgraph/cli/node_modules/@oclif/core/lib/config/config.js:268:25)
    at async Object.run (/usr/lib/node_modules/@cloudgraph/cli/node_modules/@oclif/core/lib/main.js:73:5)
⚠ There was an error installing or requiring a plugin for aws, does one exist?
ℹ For more information on this error, please see https://github.com/cloudgraphdev/cli#common-errors
⚠ There was an issue initializing aws plugin, skipping...
ℹ CloudGraph config found...
? Would you like to change CloudGraph config No
ℹ Note that none of your cloud's information is ever sent to or stored by CloudGraph or third parties
✔ Your config has been successfully stored at /home/akulbe/.config/cloudgraph/.cloud-graphrc.json
✔ Your data will be stored at /home/akulbe/.local/share/cloudgraph/cg`

**Comment by akulbe** [comment]
@tyler-dunkel Oh yeah, and `cg -v` output for Ubuntu 21.10 is as follows:

`(.venv) akulbe@cloudvana:~$ cg -v
@cloudgraph/cli/0.21.2 linux-x64 node-v17.8.0`

**Comment by tyler-dunkel** [comment]
I am sorry to hear that! of course yes we will be patient and try to not make you do too much talking. @mfranceschit can you set this up when you have time?

**Comment by mfranceschit** [comment]
@akulbe, we will have this issue in our roadmap. Meanwhile, please join our [Slack Workspace](https://join.slack.com/t/cloudgraph-workspace/shared_invite/zt-ytjemoz7-yKWwElynDp1eHAAB55sbpg) to be in touch.
